/**
 * Per-template Open Graph images, rendered at build (map Section 12: brand + page title; no screenshot services).
 * Styled after the brand banner: white field, wordmark, heavy italic caps title, red/black bottom band.
 * Colors are read from src/styles/tokens.css and logos from public/brand/ (generated by `npm run brand`).
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import satori from 'satori';
import { Resvg } from '@resvg/resvg-js';
import type { Page } from './sitemap';
import { templateEyebrow } from './labels';
import { metro } from './site';

export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

export const ogImagePath = (page: Page) => `/og/${page.slug ?? 'index'}.png`;

type Font = { name: string; data: Buffer; weight: 400 | 700 | 800; style: 'normal' | 'italic' };
const root = process.cwd();
let cache: { colors: Record<string, string>; fonts: Font[]; wordmark: string; mark: string } | undefined;

function assets() {
  if (cache) return cache;
  const css = readFileSync(join(root, 'src/styles/tokens.css'), 'utf8');
  const colors = Object.fromEntries([...css.matchAll(/--color-([a-z-]+):\s*(#[0-9a-fA-F]{3,8})/g)].map((m) => [m[1], m[2]]));
  for (const k of ['bg', 'ink', 'inverse', 'brand', 'night', 'muted']) {
    if (!colors[k]) throw new Error(`OG image needs --color-${k} as a hex value in tokens.css`);
  }
  const file = (p: string) => readFileSync(join(root, p));
  const dataUri = (p: string) => `data:image/png;base64,${file(p).toString('base64')}`;
  cache = {
    colors,
    fonts: [
      { name: 'Inter', data: file('node_modules/@fontsource/inter/files/inter-latin-400-normal.woff'), weight: 400, style: 'normal' },
      { name: 'Inter', data: file('node_modules/@fontsource/inter/files/inter-latin-700-normal.woff'), weight: 700, style: 'normal' },
      { name: 'Saira', data: file('node_modules/@fontsource/saira/files/saira-latin-800-italic.woff'), weight: 800, style: 'italic' },
    ],
    wordmark: dataUri('public/brand/wordmark.png'),
    mark: dataUri('public/brand/mark.png'),
  };
  return cache;
}

type El = { type: string; props: Record<string, unknown> };
const el = (type: string, style: Record<string, unknown>, children?: unknown, extra: Record<string, unknown> = {}): El => ({
  type,
  props: { style, children, ...extra },
});
const display = { fontFamily: 'Saira', fontStyle: 'italic', fontWeight: 800, textTransform: 'uppercase' } as const;

export async function renderOgImage(page: Page): Promise<Buffer> {
  const { colors: c, fonts, wordmark, mark } = assets();
  const title = page.h1.replace(/\[TODO: [^\]]+\]/g, '').trim();
  const size = title.length > 70 ? 50 : title.length > 40 ? 60 : 72;

  const tree = el('div', { width: '100%', height: '100%', display: 'flex', flexDirection: 'column', backgroundColor: c.bg, fontFamily: 'Inter' }, [
    el('div', { display: 'flex', height: 10, backgroundColor: c.brand }),
    el('div', { display: 'flex', flex: 1, padding: '44px 64px 32px', position: 'relative' }, [
      el('img', { position: 'absolute', right: 40, top: 40, opacity: 0.12 }, undefined, { src: mark, width: 520, height: 292 }),
      el('div', { display: 'flex', flexDirection: 'column', justifyContent: 'space-between', width: '100%' }, [
        el('img', {}, undefined, { src: wordmark, width: 300, height: 72 }),
        el('div', { display: 'flex', flexDirection: 'column' }, [
          el('div', { ...display, display: 'flex', fontSize: 28, color: c.brand, letterSpacing: '0.04em' }, templateEyebrow(page)),
          el('div', { ...display, display: 'flex', marginTop: 8, fontSize: size, lineHeight: 1.02, color: c.ink, maxWidth: 1060 }, title),
        ]),
      ]),
    ]),
    el('div', { display: 'flex', height: 96 }, [
      el('div', { ...display, display: 'flex', alignItems: 'center', flex: 1, paddingLeft: 64, backgroundColor: c.brand, color: c.inverse, fontSize: 34, letterSpacing: '0.04em' }, `Truck & driver on demand · ${metro.value ?? ''}`),
      el('div', { ...display, display: 'flex', alignItems: 'center', padding: '0 64px', backgroundColor: c.night, color: c.inverse, fontSize: 34, textTransform: 'none' }, 'boxhauls.com'),
    ]),
  ]);

  const svg = await satori(tree as never, { width: OG_WIDTH, height: OG_HEIGHT, fonts });
  return new Resvg(svg, { fitTo: { mode: 'width', value: OG_WIDTH } }).render().asPng();
}
