// Cloudflare config from docs/sitemap.json (map Section 12.1). Runs after `astro build`.
//
// Cloudflare `_redirects` matches paths only, never hostnames, so the cross-domain map (truck-n-go.com →
// boxhauls.com) and www → apex can't live there. They go in a Bulk Redirects CSV that is uploaded once in the
// dashboard (see deploy/cloudflare/README.md). `_redirects` keeps only old paths that can't collide with a real
// route, for old links that already point at boxhauls.com.
//
// Outputs:
//   dist/_redirects                         path redirects served by Cloudflare with the static site
//   dist/_headers                           noindex for app routes, cache and security headers
//   deploy/cloudflare/bulk-redirects-*.csv  cross-domain + www rules for Cloudflare Bulk Redirects (3 ordered lists)
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';

const map = JSON.parse(readFileSync('docs/sitemap.json', 'utf8'));
const placeholders = JSON.parse(readFileSync('docs/placeholders.json', 'utf8'));
const DOMAIN = placeholders.DOMAIN;
const OLD_DOMAIN = 'truck-n-go.com';
const sub = (s) => s.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (_, k) => {
  if (typeof placeholders[k] !== 'string' || placeholders[k].startsWith('TODO')) throw new Error(`Redirect uses unresolved {{${k}}}`);
  return placeholders[k];
});

const routes = new Set(map.pages.map((p) => sub(p.url)));
if (!existsSync('dist')) throw new Error('Run astro build first');

// Normalize the map: strip annotations ("(301; do not recreate)"), drop "keep" rows (handled in _headers).
const rules = [];
for (const r of map.redirects) {
  const from = sub(r.from).replace(/\s*\(.*$/, '').trim();
  const to = sub(r.to).replace(/\s*\(.*$/, '').trim();
  if (!to.startsWith('/')) continue; // "keep on new domain, noindex" / "keep, noindex"
  if (!routes.has(to)) throw new Error(`Redirect target ${to} is not a page in sitemap.json`);
  rules.push({ from, to, splat: from.endsWith('/*') });
}

// --- Bulk Redirects CSVs ------------------------------------------------------------------------------
// Columns (no header row): source_url,target_url,status_code,preserve_query_string,include_subdomains,
//                          subpath_matching,preserve_path_suffix
// Three lists, each used by its own Bulk Redirect Rule, ordered 1 → 3. Rules run in order and stop at the first
// match, which makes precedence explicit: an exact path beats its section, and a section beats the catch-all.
//   1-exact     every mapped path (with and without trailing slash) + www → apex
//   2-sections  subpath rules from the map ("/blog/*", "/cities/*")
//   3-catchall  any other truck-n-go.com path → the boxhauls.com homepage (decided 2026-10-03)
const lists = { '1-exact': [], '2-sections': [], '3-catchall': [] };
const row = (list, source, target, { subpath = false, suffix = false } = {}) =>
  lists[list].push([source, target, 301, true, true, subpath, suffix].join(','));

row('1-exact', `www.${DOMAIN}/`, `https://${DOMAIN}/`, { subpath: true, suffix: true });
for (const { from, to, splat } of rules) {
  const target = `https://${DOMAIN}${to}`;
  if (splat) {
    row('2-sections', `${OLD_DOMAIN}${from.slice(0, -1)}`, target, { subpath: true }); // "/blog/*" → "/blog/"
    continue;
  }
  if (from === '/') continue; // the catch-all covers the bare domain
  row('1-exact', `${OLD_DOMAIN}${from}`, target);
  row('1-exact', `${OLD_DOMAIN}${from}/`, target);
}
row('3-catchall', `${OLD_DOMAIN}/`, `https://${DOMAIN}/`, { subpath: true });

mkdirSync('deploy/cloudflare', { recursive: true });
if (existsSync('deploy/cloudflare/bulk-redirects.csv')) rmSync('deploy/cloudflare/bulk-redirects.csv');
for (const [name, rows] of Object.entries(lists)) writeFileSync(`deploy/cloudflare/bulk-redirects-${name}.csv`, rows.join('\n') + '\n');
const csvCount = Object.values(lists).reduce((n, l) => n + l.length, 0);

// --- _redirects ---------------------------------------------------------------------------------------
// Only old paths that differ from the target by more than a trailing slash and can't shadow a real route.
const shadows = (from) => {
  const base = from.replace(/\/\*$/, '/').replace(/\/?$/, '/');
  return [...routes].some((r) => r === base || (from.endsWith('/*') && r.startsWith(base) && r !== base));
};
const lines = ['# Generated by scripts/cloudflare.mjs from docs/sitemap.json. Do not edit.'];
for (const { from, to, splat } of rules) {
  if (from.replace(/\/?$/, '/') === to) continue; // trailing-slash only; Cloudflare serves /x/ for /x
  if (shadows(from)) continue;
  lines.push(`${from} ${to} 301`);
  if (!splat && from !== '/') lines.push(`${from}/ ${to} 301`);
}
writeFileSync('dist/_redirects', lines.join('\n') + '\n');

// --- _headers -----------------------------------------------------------------------------------------
const noindex = ['/book/*', '/embed/*', '/auth', '/auth/*', '/account', '/account/*', '/api/*'];
const headers = [
  '# Generated by scripts/cloudflare.mjs. Do not edit.',
  '/*',
  '  X-Content-Type-Options: nosniff',
  '  Referrer-Policy: strict-origin-when-cross-origin',
  '  Permissions-Policy: camera=(), microphone=(), geolocation=(self)',
  '',
  ...noindex.flatMap((p) => [p, '  X-Robots-Tag: noindex', '']),
  '/_astro/*',
  '  Cache-Control: public, max-age=31536000, immutable',
  '',
  '/brand/*',
  '  Cache-Control: public, max-age=604800',
  '',
  '/og/*',
  '  Cache-Control: public, max-age=86400',
  '',
];
writeFileSync('dist/_headers', headers.join('\n'));

console.log(`cloudflare: ${csvCount} bulk redirects in 3 lists, ${lines.length - 1} _redirects rules, _headers written`);
