// Writes docs/TODO.md from the built site: every visible [TODO: …] marker, grouped by kind and page.
// Runs after `astro build`. Marker kinds:
//   [TODO: KEY]               unknown fact from docs/placeholders.json
//   [TODO: spec — …]          the sitemap conflicts with a CLAUDE.md rule
//   [TODO: write — …]         content block not written yet
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';
const OUT = 'docs/TODO.md';

function htmlFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return name === 'og' || name === '_astro' ? [] : htmlFiles(p);
    return name === 'index.html' ? [p] : [];
  });
}

const decode = (s) => s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'");

const pages = htmlFiles(DIST).map((file) => {
  const html = readFileSync(file, 'utf8');
  const url = '/' + relative(DIST, file).replace(/index\.html$/, '');
  const phase = Number(html.match(/data-phase="(\d)"/)?.[1] ?? 0);
  const indexable = !/<meta name="robots" content="noindex"/.test(html);
  // Markers inside the collapsed sitemap-spec box restate the sitemap and are not separate TODOs.
  const body = html.replace(/<details class="mt-10 rounded-md border border-dashed[\s\S]*?<\/details>/, '');
  const markers = [...body.matchAll(/<span class="todo">\[TODO: ([^\]<]+)\]<\/span>/g)].map((m) => decode(m[1]));
  const main = html.match(/<main[\s\S]*?<\/main>/)?.[0] ?? '';
  const links = [...main.matchAll(/href="(\/[^"#?]*)"/g)].map((m) => m[1]);
  return { url, phase, indexable, markers, links };
});
// App UI like /book/ has no sitemap phase; it isn't a site page for this report.
const sitePages = pages.filter((p) => p.phase > 0);
pages.length = 0;
pages.push(...sitePages);
pages.sort((a, b) => a.phase - b.phase || a.url.localeCompare(b.url));
const byUrl = new Map(pages.map((p) => [p.url, p]));

const KEY = /^[A-Z][A-Z0-9_]*(\.[a-z_]+)?$/; // a docs/placeholders.json key, e.g. SOCIAL.app_store
const facts = new Map(); // placeholder key -> Set(url)
const questions = new Map(); // url -> [open question text]
const spec = []; // [url, text]
const content = new Map(); // url -> count
for (const p of pages) {
  for (const m of new Set(p.markers)) {
    if (m.startsWith('write — ')) continue;
    if (m.startsWith('spec — ')) spec.push([p.url, m.slice(7)]);
    else if (KEY.test(m)) (facts.get(m) ?? facts.set(m, new Set()).get(m)).add(p.url);
    else (questions.get(p.url) ?? questions.set(p.url, []).get(p.url)).push(m);
  }
  content.set(p.url, p.markers.filter((m) => m.startsWith('write — ')).length);
}

// Phase-1 pages that link (in body) to pages that are not indexable yet.
const earlyLinks = pages
  .filter((p) => p.indexable)
  .flatMap((p) => [...new Set(p.links)].filter((h) => byUrl.get(h) && !byUrl.get(h).indexable).map((h) => [p.url, h]));

const lines = [];
const out = (s = '') => lines.push(s);
out('# TODO');
out();
out('Generated by `scripts/todo.mjs` after every build. Do not edit by hand; fix the source and rebuild.');
out('A page with any visible TODO is not shippable. Open decisions live in `docs/PLAN.md`.');
out();

out(`## Unknown placeholder values (${facts.size})`);
out();
out('Fill these in `docs/placeholders.json`; every page that uses them updates on the next build.');
out();
if (!facts.size) out('None.');
for (const [key, urls] of [...facts].sort()) {
  const list = [...urls];
  const scope = list.length === pages.length ? 'every page' : list.length > 6 ? `${list.length} pages` : list.join(', ');
  out(`- \`${key}\`: ${scope}`);
}
out();

// Open questions, grouped by page (Phase 1 first). The same question on many pages is listed once per page.
const qCount = [...questions.values()].reduce((n, q) => n + q.length, 0);
const distinct = new Set([...questions.values()].flat());
out(`## Open facts by page (${qCount} markers, ${distinct.size} distinct questions)`);
out();
out("Facts the copy needs that aren't in `docs/placeholders.json` yet. Answer them, then the copy is updated and the marker removed.");
out();
for (const phase of [1, 2, 3]) {
  const rows = pages.filter((p) => p.phase === phase && questions.has(p.url));
  if (!rows.length) continue;
  out(`### Phase ${phase}`);
  out();
  for (const p of rows) {
    out(`**${p.url}**`);
    for (const q of questions.get(p.url)) out(`- ${q}`);
    out();
  }
}

out(`## Spec conflicts (${spec.length})`);
out();
out('The sitemap asks for something a CLAUDE.md rule forbids. Fix it in `build_map.py`, then `npm run map`.');
out();
if (!spec.length) out('None.');
for (const [url, text] of spec) out(`- ${url}: ${text}`);
out();

out(`## Live pages linking to pages that are not live (${earlyLinks.length})`);
out();
out('Should always be zero: a Phase-1 page must not link to a noindex stub. If this lists anything, a component is linking around the deferral rule.');
out();
if (!earlyLinks.length) out('None.');
for (const [from, to] of earlyLinks) out(`- ${from} → ${to}`);
out();

// links_to targets on live pages whose target isn't live yet, straight from the sitemap.
const spec_ = JSON.parse(readFileSync('docs/sitemap.json', 'utf8'));
const ph_ = JSON.parse(readFileSync('docs/placeholders.json', 'utf8'));
const sub_ = (u) => u.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (_, k) => ph_[k]);
const phaseOf = new Map(spec_.pages.map((p) => [sub_(p.url), p.phase]));
const deferred = spec_.pages
  .filter((p) => p.phase === 1)
  .flatMap((p) => p.links_to.map(sub_).filter((t) => phaseOf.get(t) > 1).map((t) => [sub_(p.url), t]));
out(`## Deferred links (${deferred.length}, not blockers)`);
out();
out("These `links_to` targets are Phase 2/3. The link is held back and appears automatically when the target's phase ships.");
out();
if (!deferred.length) out('None.');
for (const [from, to] of deferred) out(`- ${from} → ${to}`);
out();

out('## Unwritten content blocks');
out();
out('| Page | Phase | Blocks to write |');
out('|---|---|---|');
for (const p of pages.filter((p) => p.phase === 1)) out(`| ${p.url} | 1 | ${content.get(p.url)} |`);
const later = pages.filter((p) => p.phase > 1);
out();
out(`Phase 2–3: ${later.length} pages, ${later.reduce((n, p) => n + content.get(p.url), 0)} blocks (not listed until Phase 1 passes QA).`);
out();

writeFileSync(OUT, lines.join('\n'));

// docs/LAUNCH.md section 7: every Phase-1 TODO and the page it blocks, rewritten between markers.
const LAUNCH = 'docs/LAUNCH.md';
try {
  const launch = readFileSync(LAUNCH, 'utf8');
  const blocked = pages.filter((p) => p.phase === 1 && p.markers.some((m) => !m.startsWith('write — ')));
  const block = ['<!-- TODO:START -->', ''];
  block.push(`${blocked.length} of ${pages.filter((p) => p.phase === 1).length} Phase-1 pages are blocked by visible TODO markers.`, '');
  const shared = [...facts].filter(([, urls]) => urls.size > 6).map(([k, urls]) => `\`${k}\` (${urls.size} pages, in the footer)`);
  if (shared.length) block.push(`**On nearly every page:** ${shared.join(', ')}.`, '');
  block.push('| Page | Blocked by |', '|---|---|');
  for (const p of blocked) {
    const items = [...new Set(p.markers.filter((m) => !m.startsWith('write — ') && !(facts.get(m)?.size > 6)))];
    if (items.length) block.push(`| ${p.url} | ${items.join('; ').replace(/\|/g, '\\|')} |`);
  }
  block.push('', '<!-- TODO:END -->');
  writeFileSync(LAUNCH, launch.replace(/<!-- TODO:START -->[\s\S]*<!-- TODO:END -->/, block.join('\n')));
} catch (e) {
  if (e.code !== 'ENOENT') throw e;
}
console.log(`todo: wrote ${OUT} — ${facts.size} placeholder keys, ${distinct.size} open questions, ${spec.length} spec conflicts, ${earlyLinks.length} live→stub links, ${deferred.length} deferred`);
