// Writes docs/TODO.md from the built site: every visible [TODO: …] marker, grouped by kind and page.
// Runs after `astro build`. Marker kinds:
//   [TODO: KEY]               unknown fact from docs/placeholders.json
//   [TODO: spec — …]          the sitemap conflicts with a CLAUDE.md rule
//   [TODO: write — …]         content block not written yet
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';
const OUT = 'docs/TODO.md';

function htmlFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return name === 'og' || name === '_astro' ? [] : htmlFiles(p);
    return name === 'index.html' ? [p] : [];
  });
}

const decode = (s) => s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'");

const pages = htmlFiles(DIST).map((file) => {
  const html = readFileSync(file, 'utf8');
  const url = '/' + relative(DIST, file).replace(/index\.html$/, '');
  const phase = Number(html.match(/data-phase="(\d)"/)?.[1] ?? 0);
  const indexable = !/<meta name="robots" content="noindex"/.test(html);
  // Markers inside the collapsed sitemap-spec box restate the sitemap and are not separate TODOs.
  const body = html.replace(/<details class="mt-10 rounded-md border border-dashed[\s\S]*?<\/details>/, '');
  const markers = [...body.matchAll(/<span class="todo">\[TODO: ([^\]<]+)\]<\/span>/g)].map((m) => decode(m[1]));
  const main = html.match(/<main[\s\S]*?<\/main>/)?.[0] ?? '';
  const links = [...main.matchAll(/href="(\/[^"#?]*)"/g)].map((m) => m[1]);
  const deferred = (html.match(/data-deferred-links="([^"]+)"/)?.[1] ?? '').split(' ').filter(Boolean);
  return { url, phase, indexable, markers, links, deferred };
});
pages.sort((a, b) => a.phase - b.phase || a.url.localeCompare(b.url));
const byUrl = new Map(pages.map((p) => [p.url, p]));

const facts = new Map(); // key -> Set(url)
const spec = []; // [url, text]
const content = new Map(); // url -> count
for (const p of pages) {
  for (const m of new Set(p.markers)) {
    if (m.startsWith('write — ')) continue;
    if (m.startsWith('spec — ')) spec.push([p.url, m.slice(7)]);
    else (facts.get(m) ?? facts.set(m, new Set()).get(m)).add(p.url);
  }
  content.set(p.url, p.markers.filter((m) => m.startsWith('write — ')).length);
}

// Phase-1 pages that link (in body) to pages that are not indexable yet.
const earlyLinks = pages
  .filter((p) => p.indexable)
  .flatMap((p) => [...new Set(p.links)].filter((h) => byUrl.get(h) && !byUrl.get(h).indexable).map((h) => [p.url, h]));

const lines = [];
const out = (s = '') => lines.push(s);
out('# TODO');
out();
out('Generated by `scripts/todo.mjs` after every build. Do not edit by hand; fix the source and rebuild.');
out('A page with any visible TODO is not shippable. Open decisions live in `docs/PLAN.md`.');
out();

out(`## Unknown facts (${facts.size})`);
out();
out('Fill these in `docs/placeholders.json`.');
out();
if (!facts.size) out('None.');
for (const [key, urls] of [...facts].sort()) {
  const list = [...urls];
  const scope = list.length === pages.length ? 'every page' : list.length > 6 ? `${list.length} pages` : list.join(', ');
  out(`- \`${key}\`: ${scope}`);
}
out();

out(`## Spec conflicts (${spec.length})`);
out();
out('The sitemap asks for something a CLAUDE.md rule forbids. Fix it in `build_map.py`, then `npm run map`.');
out();
if (!spec.length) out('None.');
for (const [url, text] of spec) out(`- ${url}: ${text}`);
out();

out(`## Live pages linking to pages that are not live (${earlyLinks.length})`);
out();
out('Should always be zero: a Phase-1 page must not link to a noindex stub. If this lists anything, a component is linking around the deferral rule.');
out();
if (!earlyLinks.length) out('None.');
for (const [from, to] of earlyLinks) out(`- ${from} → ${to}`);
out();

const deferred = pages.flatMap((p) => p.deferred.map((to) => [p.url, to]));
out(`## Deferred links (${deferred.length}, not blockers)`);
out();
out("These `links_to` targets are Phase 2/3. The link is held back and appears automatically when the target's phase ships.");
out();
if (!deferred.length) out('None.');
for (const [from, to] of deferred) out(`- ${from} → ${to}`);
out();

out('## Unwritten content blocks');
out();
out('| Page | Phase | Blocks to write |');
out('|---|---|---|');
for (const p of pages.filter((p) => p.phase === 1)) out(`| ${p.url} | 1 | ${content.get(p.url)} |`);
const later = pages.filter((p) => p.phase > 1);
out();
out(`Phase 2–3: ${later.length} pages, ${later.reduce((n, p) => n + content.get(p.url), 0)} blocks (not listed until Phase 1 passes QA).`);
out();

writeFileSync(OUT, lines.join('\n'));
console.log(`todo: wrote ${OUT} — ${facts.size} unknown facts, ${spec.length} spec conflicts, ${earlyLinks.length} live→stub links, ${deferred.length} deferred`);
